### ISSUE TITLE
Right Calendar Does not Jump to Corresponding Month if "To:" Date is Undefined

### ISSUE THREAD

**Issue by PimpMastre** [alsoicode/ngx-daterange#37]
When selecting a date in the "From:" calendar, if that date is set after the "To:" date, it will automatically jump to the corresponding month. This does not happen when the "To:" date is undefined, requiring the user to manually go to the month displayed in the "From" field.

This only happens when selecting a future month in the left calendar.

![image](https://user-images.githubusercontent.com/24656910/88274411-58a46500-cce4-11ea-88b2-d48e6272dd5b.png)

**Comment by alsoicode** [comment]
Good catch. I'll try to work on that soon.

**Comment by alsoicode** [comment]
@PimpMastre This has been fixed in 1.0.27: https://www.npmjs.com/package/ngx-daterange

**Comment by PimpMastre** [comment]
Issue is only partially fixed.

Selecting a date in the left calendar will only trigger a change in the right one if the year selected in the left is greater than the one displayed in the right calendar. If you select a date that is in the same year but different month, the right calendar will still be left unchanged (only when undefined).

**Comment by alsoicode** [comment]
@PimpMastre Good catch! This is fixed in 1.0.28
